package PLMTK;
use strict;
use warnings;
# parameter settings for users
our $speaker_name     = '123';
our $databasedir      = '/home/jiajusu/slmtk/egs/general/worksite/123';
our $progbasedir      = '/home/jiajusu/slmtk/programs';
our $MATLABDIR        = '/usr/local/MATLAB/R2020b/bin';
our $LOWERF0HZ        = 60;
our $UPPERF0HZ        = 550;
our $ADP_PORTION      = 9;
our $TEST_PORTION     = 1;
our $PURE_ENG_UTT_STR = 'NULL';
our $AUDIO_NORMALIZATION_GAIN = 1.0;
# HTS parameters
our $with_sptk_search_path ='/usr/local/share/SPTK';
our $with_hts_search_path ='/usr/local/HTS-2.2beta/bin/';
our $with_hts_engine_search_path ='/usr/local/bin/';
our $with_tcl_search_path ='/opt/ActiveTcl-8.4/bin/';
our $with_fest_search_path ='/home/jiajusu/slmtk/programs/hts/HTS-2.2/Other-dependents/festival-2.1/festival/examples/';
our $SDT_Training = 1;
our $SAT_Training = 1;
our $SAT_with_prior = 1;
our $HTS_SAT_without_prior_basedir = '/home/jiajusu/slmtk/egs/general/worksite/HTS_SAT_without_prior';
# commands
our $DIVIDE_ENGCH     = '/dp/divide_engch/divide_engch';
our $PARSER           = '/ta/parser_UNICODE/parser_example';
our $PARSER2TRANSX    = '/ta/parser2transx/parser2transx';
our $POLY             = '/ta/poly/poly';
our $TONESANDHI       = '/ta/tonesandhi/tonesandhi';
our $PHONEME_GEN      = '/ta/phoneme_gen/phoneme_gen';
our $PHONEME2ALA      = '/ta/phoneme2ala/phoneme2ala';
our $RMSPACE_ALA      = '/dp/rmspace_ala/rmspace_ala';
our $ALA2TXT          = '/dp/ala2txt/ala2txt';
our $TOKENIZE         = '/dp/tokenize/text_tokenize';
our $TOK2MLF          = '/dp/tok2mlf/tok2mlf';
our $MLF2BYTE         = '/dp/mlf2byte/mlf2byte';
our $MLF2TOTAL        = '/dp/mlf2total/mlf2total';
our $CHECK_DICT       = '/dp/check_dict/check_dict';
our $CHDICT2BYTE      = '/dp/chdict2byte/chdict2byte';
our $BU2CMU           = '/dp/bu2cmu/bu2cmu';
our $MKWSJDICT        = 'dp/mkwsjdict/mkwsjdict';
our $LABWSJ2PLMTK     = 'dp/labwsj2plmtk/labwsj2plmtk';
our $SOX              = 'sox';
our $HCOPY            = 'HCopy';
our $HVITE            = 'HVite';
our $LABDISP          = '/dp/labdisp/labdisp';
our $LAB2SYM          = '/dp/lab2symbol/lab2symbol';
our $UVREFINE         = '/dp/uvrefine/uvrefine';
our $SPREFINE         = '/dp/sprefine/sprefine';
our $MULGEN           = '/dp/mulgen/mulgen';
our $MUL2TEXTGRID     = '/dp/mul2TextGrid/mul2TextGrid';
our $PITCH            = 'pitch';
our $F0FILTER         = '/dp/f0filter/f0filter';
our $F0TKLOG          = '/dp/f0takenlog/f0takenlog';
our $X2X              = 'x2x';
our $PWR              = '/dp/pwr/pwr';
our $MKAL             = '/dp/mkal/mkal';
our $GENPHTB          = '/plm/gentable/GeneratePhoneticTables.m';
our $DATASET          = '/plm/dataset/DataSet.m';
our $MATLAB           = '/matlab -nodesktop';
our $FRMLF0MUSTD      = '/dp/frmlf0mustd/frmlf0mustd';
our $FRMLF0NRM        = '/dp/frmlf0nrm/frmlf0nrm';
our $DATASTATS        = '/plm/dataset/datastats.m';
our $NORMADP          = '/plm/normadp/normadp.m';
our $NORMADP_B        = '/plm/normadp_B/normadp.m';
our $FEANORM          = '/plm/feanorm/feanorm.m';
our $PH2HMM           = '/plm/mkhtslab/gen_ph2HMMUnit.m';
our $MKHTSLAB         = '/plm/mkhtslab/mkhtslab_new';
our $ZEROAMPSILSP     = '/plm/zeroampsilsp/zeroampsilsp';
our $RMLONGSIL        = '/plm/rmlongsil/rmlongsil';
our $HTSRENAME        = '/plm/htsrename/htsrename.m';
our $DADATACHECK      = '/dnnam/dadatacheck/dadatacheck';
our $DATAAUGLN        = '/vm/dataaugln/dataaugln.pl';
our $PM2COS           = '/vm/pm2cos/pm2cos';
our $PM2LAB           = '/vm/pm2cos/pm2lab';
our $MKATT            = '/dp/segrefine/mkatt/mkatt.sh';
our $TEXTGRIDNORM     = '/dp/TextGridNorm/TextGridNorm';
our $TEXTGRID2MUL     = '/dp/TextGrid2mul/TextGrid2mul';
# Switch ================================
    # text analysis
        our $CLEAN = 0;
        our $INSSP = 0;
        our $PARSE = 0;
        our $TONES = 0;
        our $PA2TX = 0;
        our $PHGEN = 0;
        our $PH2AL = 0;
        our $RMASP = 0;
    # speech segmentation
        our $ALA2T = 1;
        our $TOKEN = 1;
        our $T2MLF = 1;
        our $ML2BT = 1;
        our $ML2TT = 1;
        our $CKDIC = 1;
        our $CDBYT = 1;
        our $B2CMU = 1;
        our $SOX16 = 1;
        our $SOX20 = 1;
        our $HTKTB = 1;
        our $WSJFA = 0;
        our $SGREF = 1;
        our $SPREF = 0;
        our $UVREF = 0;
    # integration_of_linguistic_features_and_prosodic_features
        our $TXGNM = 0;
        our $TXG2M = 0;
        our $MULGN = 0;
        our $M2TXG = 0;
        our $F0EXT = 0;
        our $F0PMK = 0;
        our $F0FLT = 0;
        our $F0TKL = 0;
        our $FRMPR = 0;
        our $MKALP = 0;
        our $GENTB = 0;
        our $DTSET = 0;
        our $LF0NM = 0;
        our $MKALS = 0;
    # prosody labeling and modeling
        our $ALSTS   = 0;
        our $TRECG   = 0;
        our $NRADP   = 0;
        our $FEANR   = 0;
        our $PLMAD   = 0;
        our $NRADP_B = 0;
        our $FEANR_B = 0;
        our $PLMAD_B = 0;
        our $TRXPB   = 0;
    # construction of prosody generation models
        our $BTADP      = 0;
        our $PSADP      = 0;
        our $MDPRE      = 0;
        our $MDPRE_RV   = 0;
        our $MKBPRV     = 0;
        our $MKPSPRV    = 0;
        our $MKPAFRV    = 0;
        our $MKPG_RVTW  = 0;
    # HTS training
        our $MKLAB              = 0;
        our $ZRAMP              = 0;
        our $RMSIL              = 0;
        our $AUNRM              = 0;
        our $MKHTS              = 0;
        our $RNHTS              = 0;
        our $MKHTSEGPC_RV       = 0;
        our $MKHTSEGPC_RVTW_SD  = 0;
        our $MKHTSEGPC_RVTW_SAT = 0;
    # training_of_vocoding_model
        our $AUGVM = 0;
        our $MVMPM = 0;
        our $DCHCK = 0;
1;
